# https://taskfile.dev
version: "3"
tasks:
  default:
    deps:
      - build
    cmds:
      - bin/eops

  sh: iex -S mix
  # put into local paths
  build: mix escript.build --force
  # install into PATH
  # mix do escript.build + escript.install
  install: mix escript.build escript.install bin/eops --force
  script: mix escript

  create: mix new hello-cli-elixir --app hello_cli
